export const data = [
  {
    id: 1,
    project: "Project Alpha",
    cluster: "Kerala",
    region: "South",
    facilitator: "Facilitator 1",
    status: "Approved",
    goals: {
      "2024": {
        January: [
          {
            goal: "Increase local engagement",
            majorGoal: true,
            functionalArea: "Community Outreach",
            achieved: "yes",
            reason: "Strong volunteer participation",
            comments: "Exceeded expectations",
          },
          {
            goal: "Host a workshop",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "no",
            reason: "Scheduling conflicts",
            comments: "Will reschedule next month",
          },
          {
            goal: "Develop new partnerships",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "Effective networking",
            comments: "Two new MOUs signed",
          },
        ],
        February: [
          {
            goal: "Increase local engagement",
            majorGoal: false,
            functionalArea: "Community Outreach",
            achieved: "yes",
            reason: "Strong volunteer participation",
            comments: "Exceeded expectations",
          },
          {
            goal: "Host a workshop",
            majorGoal: true,
            functionalArea: "Education",
            achieved: "no",
            reason: "Scheduling conflicts",
            comments: "Will reschedule next month",
          },
          {
            goal: "Develop new partnerships",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "Effective networking",
            comments: "Two new MOUs signed",
          },
        ],
      },
      "2023": {
        November: [
          {
            goal: "Increase local engagement",
            majorGoal: true,
            functionalArea: "Community Outreach",
            achieved: "yes",
            reason: "Strong volunteer participation",
            comments: "Exceeded expectations",
          },
          {
            goal: "Host a workshop",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "no",
            reason: "Scheduling conflicts",
            comments: "Will reschedule next month",
          },
          {
            goal: "Develop new partnerships",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "Effective networking",
            comments: "Two new MOUs signed",
          },
        ],
        December: [
          {
            goal: "Organize a fundraising event",
            majorGoal: false,
            functionalArea: "Fundraising",
            achieved: "yes",
            reason: "High donor turnout",
            comments: "Raised 20% more than target",
          },
          {
            goal: "Launch awareness campaign",
            majorGoal: false,
            functionalArea: "Marketing",
            achieved: "no",
            reason: "Budget constraints",
            comments: "Postponed to next quarter",
          },
          {
            goal: "Recruit volunteers",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Successful outreach",
            comments: "Added 15 new volunteers",
          },
        ],
      },
    },
    nextMonth: {
      goals: [
        {
          goal: "Conduct training sessions",
          majorGoal: false,
          functionalArea: "Education",
          comments: "Focus on digital skills",
        },
        {
          goal: "Improve donor retention",
          majorGoal: false,
          functionalArea: "Fundraising",
          comments: "Send personalized thank-you notes",
        },
        {
          goal: "Expand social media reach",
          majorGoal: true,
          functionalArea: "Marketing",
          comments: "Target younger demographics",
        },
      ],
      additionalActivities: [
        {
          goal: "Organize health camp",
          majorGoal: true,
          functionalArea: "Community Health",
          comments: "Collaborate with local hospitals",
        },
        {
          goal: "Introduce feedback mechanisms",
          majorGoal: false,
          functionalArea: "Quality Assurance",
          comments: "Deploy online surveys",
        },
        {
          goal: "Host community cleanup drive",
          majorGoal: false,
          functionalArea: "Environment",
          comments: "Engage local schools",
        },
      ],
    },
    prayerRequests: [
      "Pray for continued volunteer engagement",
      "Pray for smooth rescheduling of the workshop",
    ],
    praisePoints: [
      "Praise for high donor turnout in the fundraising event",
      "Praise for the new partnerships formed",
    ],
    story:
      "A testimony of how our outreach efforts led to two significant partnerships that will benefit the community.",
    concerns:
      "Concerns about the postponed awareness campaign and the budget constraints.",
  },
  {
    id: 2,
    project: "Project Beta",
    cluster: "Tamil Nadu",
    region: "South",
    facilitator: "Facilitator 2",
    status: "Pending",
    goals: {
      "2024": {
        January: [
          {
            goal: "Host a leadership seminar",
            majorGoal: false,
            functionalArea: "Leadership Development",
            achieved: "yes",
            reason: "Strong speaker lineup",
            comments: "Well received by attendees",
          },
          {
            goal: "Launch environmental initiative",
            majorGoal: false,
            functionalArea: "Environment",
            achieved: "no",
            reason: "Lack of initial funding",
            comments: "Seeking alternative sponsors",
          },
          {
            goal: "Enhance team collaboration",
            majorGoal: true,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Team-building activities",
            comments: "Improved cross-team communication",
          },
        ],
        February: [
          {
            goal: "Improve local education standards",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Teacher training sessions",
            comments: "Teachers now equipped with new tools",
          },
          {
            goal: "Strengthen partnerships with NGOs",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "Mutual objectives aligned",
            comments: "Two new strategic partnerships formed",
          },
          {
            goal: "Increase fundraising efforts",
            majorGoal: false,
            functionalArea: "Fundraising",
            achieved: "no",
            reason: "Underperformed in early campaigns",
            comments: "Adjusting strategy for next month",
          },
        ],
      },
      "2023": {
        November: [
          {
            goal: "Create a mental health awareness program",
            majorGoal: false,
            functionalArea: "Health",
            achieved: "yes",
            reason: "Support from medical community",
            comments: "Successfully launched with community support",
          },
          {
            goal: "Develop digital marketing strategy",
            majorGoal: false,
            functionalArea: "Marketing",
            achieved: "no",
            reason: "Delayed due to resource constraints",
            comments: "Postponed to January",
          },
          {
            goal: "Recruit new staff for HR department",
            majorGoal: true,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Successful recruitment campaign",
            comments: "Filled all positions",
          },
        ],
        December: [
          {
            goal: "Organize a charity dinner",
            majorGoal: false,
            functionalArea: "Fundraising",
            achieved: "yes",
            reason: "Outstanding community support",
            comments: "Exceeded fundraising goal by 30%",
          },
          {
            goal: "Create a new volunteer management system",
            majorGoal: false,
            functionalArea: "IT",
            achieved: "no",
            reason: "Technical challenges",
            comments: "To be rescheduled in Q2",
          },
          {
            goal: "Establish a new corporate partnership",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "Negotiations successful",
            comments: "Secured major partnership for 2024",
          },
        ],
      },
    },
    nextMonth: {
      goals: [
        {
          goal: "Host a cultural awareness program",
          majorGoal: false,
          functionalArea: "Cultural Outreach",
          comments: "Focus on ethnic diversity",
        },
        {
          goal: "Build a more inclusive team culture",
          majorGoal: false,
          functionalArea: "HR",
          comments: "Introduce mentorship programs",
        },
        {
          goal: "Expand marketing reach through influencers",
          majorGoal: false,
          functionalArea: "Marketing",
          comments: "Engage more influencers for social media outreach",
        },
      ],
      additionalActivities: [
        {
          goal: "Launch eco-friendly packaging initiative",
          majorGoal: false,
          functionalArea: "Environment",
          comments: "Collaborate with sustainable suppliers",
        },
        {
          goal: "Provide job training for at-risk youth",
          majorGoal: false,
          functionalArea: "Community Outreach",
          comments: "Partner with local vocational schools",
        },
        {
          goal: "Create an internal wellness program",
          majorGoal: false,
          functionalArea: "HR",
          comments: "Focus on physical and mental health",
        },
      ],
    },
    prayerRequests: [
      "Pray for increased donations for the environmental project",
      "Pray for smooth execution of new marketing campaigns",
    ],
    praisePoints: [
      "Praise for the successful mental health awareness program",
      "Praise for the new corporate partnership",
    ],
    story:
      "A powerful story of how we collaborated with local schools to create a lasting impact on the community’s mental health.",
    concerns:
      "Concerns about the digital marketing strategy delays and funding shortages.",
  },
  {
    id: 3,
    project: "Project Gamma",
    cluster: "Maharashtra",
    region: "West",
    facilitator: "Facilitator 3",
    status: "Approved",
    goals: {
      "2024": {
        January: [
          {
            goal: "Increase volunteer recruitment",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Successful online campaign",
            comments: "Added 50 new volunteers",
          },
          {
            goal: "Organize leadership summit",
            majorGoal: false,
            functionalArea: "Leadership Development",
            achieved: "no",
            reason: "Venue availability issues",
            comments: "Will reschedule for February",
          },
          {
            goal: "Expand community outreach programs",
            majorGoal: false,
            functionalArea: "Community Outreach",
            achieved: "yes",
            reason: "More targeted outreach efforts",
            comments: "Successfully reached 2000 more individuals",
          },
        ],
        February: [
          {
            goal: "Launch new mentorship program",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Recruitment of expert mentors",
            comments: "Program launched with 10 active mentors",
          },
          {
            goal: "Strengthen local partnerships",
            majorGoal: false,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "New collaboration with local businesses",
            comments: "Secured 3 new partnerships",
          },
          {
            goal: "Improve digital presence",
            majorGoal: true,
            functionalArea: "Marketing",
            achieved: "no",
            reason: "Team shortage",
            comments: "Revised strategy for March",
          },
        ],
      },
      "2023": {
        November: [
          {
            goal: "Create sustainability program",
            majorGoal: false,
            functionalArea: "Environment",
            achieved: "yes",
            reason: "Support from environmental agencies",
            comments: "Launched first phase of the program",
          },
          {
            goal: "Host community wellness event",
            majorGoal: true,
            functionalArea: "Health",
            achieved: "no",
            reason: "Logistical issues",
            comments: "Postponed to next quarter",
          },
          {
            goal: "Strengthen social media presence",
            majorGoal: false,
            functionalArea: "Marketing",
            achieved: "yes",
            reason: "Improved content strategy",
            comments: "Followed by a 20% increase in engagement",
          },
        ],
        December: [
          {
            goal: "Recruit senior leadership team",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Successful executive search",
            comments: "Hired a new CEO and CFO",
          },
          {
            goal: "Organize charity marathon",
            majorGoal: false,
            functionalArea: "Fundraising",
            achieved: "yes",
            reason: "Great turnout and sponsorship",
            comments: "Raised funds for two local charities",
          },
          {
            goal: "Launch internal knowledge-sharing platform",
            majorGoal: false,
            functionalArea: "IT",
            achieved: "no",
            reason: "Technical difficulties",
            comments: "Rescheduled for Q1 2024",
          },
        ],
      },
    },
    nextMonth: {
      goals: [
        {
          goal: "Expand outreach to rural areas",
          majorGoal: false,
          functionalArea: "Community Outreach",
          comments: "Focus on education and health services",
        },
        {
          goal: "Launch employee wellness initiative",
          majorGoal: false,
          functionalArea: "HR",
          comments: "Provide mental and physical health resources",
        },
        {
          goal: "Strengthen donor engagement",
          majorGoal: false,
          functionalArea: "Fundraising",
          comments: "Implement personalized donor campaigns",
        },
      ],
      additionalActivities: [
        {
          goal: "Host food security awareness campaign",
          majorGoal: true,
          functionalArea: "Community Outreach",
          comments: "Partner with local farmers' groups",
        },
        {
          goal: "Improve volunteer retention strategies",
          majorGoal: false,
          functionalArea: "HR",
          comments: "Launch new incentives for volunteers",
        },
        {
          goal: "Create a digital toolkit for volunteers",
          majorGoal: false,
          functionalArea: "Education",
          comments: "Develop online resources for training",
        },
      ],
    },
    prayerRequests: [
      "Pray for the success of the rural outreach programs",
      "Pray for effective implementation of the employee wellness initiative",
    ],
    praisePoints: [
      "Praise for the successful recruitment of the new leadership team",
      "Praise for the charity marathon that raised significant funds",
    ],
    story:
      "Our executive leadership changes have been met with positive reactions from the community, and we expect to make a lasting impact with our new vision.",
    concerns:
      "Concerns about the delayed launch of the internal knowledge-sharing platform and its impact on collaboration.",
  },
  {
    id: 4,
    project: "Project Delta",
    cluster: "Uttar Pradesh",
    region: "North",
    facilitator: "Facilitator 4",
    status: "Approved",
    goals: {
      "2024": {
        January: [
          {
            goal: "Host a youth empowerment seminar",
            majorGoal: false,
            functionalArea: "Youth Development",
            achieved: "yes",
            reason: "Expert speakers and strong turnout",
            comments: "Participants rated the seminar highly",
          },
          {
            goal: "Expand health services to rural areas",
            majorGoal: false,
            functionalArea: "Health",
            achieved: "no",
            reason: "Delayed due to infrastructure issues",
            comments: "To be initiated in February",
          },
          {
            goal: "Strengthen environmental education programs",
            majorGoal: true,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Partnership with local schools",
            comments: "Launched in 5 schools",
          },
        ],
        February: [
          {
            goal: "Develop corporate mentorship program",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Engaged mentors from top companies",
            comments: "Launched with 12 corporate partners",
          },
          {
            goal: "Improve internal communication",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Introduction of new communication tools",
            comments: "Increased team productivity",
          },
          {
            goal: "Organize fundraising gala",
            majorGoal: true,
            functionalArea: "Fundraising",
            achieved: "no",
            reason: "Budget constraints",
            comments: "Postponed to Q2 2024",
          },
        ],
      },
      "2023": {
        November: [
          {
            goal: "Provide skill development workshops",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Strong interest from participants",
            comments: "10 workshops conducted with over 1000 participants",
          },
          {
            goal: "Strengthen volunteer network",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Targeted recruitment campaigns",
            comments: "Grew the volunteer base by 25%",
          },
          {
            goal: "Launch health awareness initiative",
            majorGoal: true,
            functionalArea: "Health",
            achieved: "yes",
            reason: "Collaboration with local clinics",
            comments: "Reached over 2000 individuals",
          },
        ],
        December: [
          {
            goal: "Implement new social media strategy",
            majorGoal: false,
            functionalArea: "Marketing",
            achieved: "yes",
            reason: "Hiring of social media manager",
            comments: "Significant increase in engagement",
          },
          {
            goal: "Expand nutrition program",
            majorGoal: false,
            functionalArea: "Health",
            achieved: "no",
            reason: "Delayed shipments",
            comments: "Postponed to Q1 2024",
          },
          {
            goal: "Host annual conference",
            majorGoal: true,
            functionalArea: "Leadership Development",
            achieved: "yes",
            reason: "Excellent organization and speakers",
            comments: "Conference was a success",
          },
        ],
      },
    },
    nextMonth: {
      goals: [
        {
          goal: "Launch online fundraising platform",
          majorGoal: false,
          functionalArea: "Fundraising",
          comments: "Streamline donations and campaigns",
        },
        {
          goal: "Increase community volunteer involvement",
          majorGoal: false,
          functionalArea: "HR",
          comments: "Create more flexible volunteer opportunities",
        },
        {
          goal: "Develop environmental sustainability initiatives",
          majorGoal: false,
          functionalArea: "Environment",
          comments: "Focus on reducing waste and energy consumption",
        },
      ],
      additionalActivities: [
        {
          goal: "Offer digital literacy training for seniors",
          majorGoal: false,
          functionalArea: "Education",
          comments: "Partner with local libraries and tech experts",
        },
        {
          goal: "Improve community health through fitness programs",
          majorGoal: false,
          functionalArea: "Health",
          comments: "Collaborate with gyms and local sports groups",
        },
        {
          goal: "Organize disaster preparedness workshops",
          majorGoal: true,
          functionalArea: "Community Outreach",
          comments: "Work with local authorities for better preparedness",
        },
      ],
    },
    prayerRequests: [
      "Pray for success in the fundraising gala rescheduled for next quarter",
      "Pray for successful implementation of the online fundraising platform",
    ],
    praisePoints: [
      "Praise for the successful youth empowerment seminar",
      "Praise for the increase in volunteer participation",
    ],
    story:
      "We are seeing amazing results from our environmental education programs, with local schools now actively engaging in sustainability projects.",
    concerns:
      "Concerns about the delayed health services expansion to rural areas due to infrastructure challenges.",
  },
  {
    id: 5,
    project: "Project Theta",
    cluster: "Karnataka",
    region: "South",
    facilitator: "Facilitator 5",
    status: "Approved",
    goals: {
      "2024": {
        January: [
          {
            goal: "Launch new leadership training program",
            majorGoal: true,
            functionalArea: "Leadership Development",
            achieved: "yes",
            reason: "Successful recruitment of expert trainers",
            comments: "The program is up and running with 15 participants",
          },
          {
            goal: "Increase community health screenings",
            majorGoal: false,
            functionalArea: "Health",
            achieved: "no",
            reason: "Supply chain delays in medical equipment",
            comments: "Rescheduled for February",
          },
          {
            goal: "Expand local agricultural support",
            majorGoal: false,
            functionalArea: "Agriculture",
            achieved: "yes",
            reason: "New partnership with local farmers' co-op",
            comments: "Support reached over 100 farms in the region",
          },
        ],
        February: [
          {
            goal: "Introduce digital education tools in schools",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Successful collaboration with tech partners",
            comments: "Launched digital tools in 5 schools",
          },
          {
            goal: "Strengthen mental health support programs",
            majorGoal: true,
            functionalArea: "Health",
            achieved: "yes",
            reason: "New funding secured for mental health initiatives",
            comments: "Launched 2 new mental health support workshops",
          },
          {
            goal: "Host annual fundraiser event",
            majorGoal: true,
            functionalArea: "Fundraising",
            achieved: "no",
            reason: "COVID-19 restrictions",
            comments: "Event postponed to Q3",
          },
        ],
      },
      "2023": {
        November: [
          {
            goal: "Develop community-based job training program",
            majorGoal: false,
            functionalArea: "HR",
            achieved: "yes",
            reason: "Strong interest from local businesses",
            comments: "Launched training with 10 local businesses involved",
          },
          {
            goal: "Provide free health checkups to underserved communities",
            majorGoal: false,
            functionalArea: "Health",
            achieved: "yes",
            reason: "Partnership with local clinics",
            comments: "Served over 500 individuals",
          },
          {
            goal: "Strengthen regional partnerships for sustainable development",
            majorGoal: true,
            functionalArea: "Partnerships",
            achieved: "yes",
            reason: "New strategic alliances formed",
            comments: "Secured 4 new partnerships",
          },
        ],
        December: [
          {
            goal: "Organize skill-building workshops for women",
            majorGoal: false,
            functionalArea: "Education",
            achieved: "yes",
            reason: "Strong turnout from the community",
            comments: "100 women trained in new skills",
          },
          {
            goal: "Improve internal operational efficiency",
            majorGoal: false,
            functionalArea: "Operations",
            achieved: "no",
            reason: "Technological upgrades delayed",
            comments: "Will be addressed in Q1 2024",
          },
          {
            goal: "Launch environmental awareness campaign",
            majorGoal: true,
            functionalArea: "Environment",
            achieved: "yes",
            reason: "Effective media outreach",
            comments: "Reached over 2000 people through local media",
          },
        ],
      },
    },
    nextMonth: {
      goals: [
        {
          goal: "Implement green energy initiatives",
          majorGoal: false,
          functionalArea: "Environment",
          comments: "Focus on solar energy and energy efficiency programs",
        },
        {
          goal: "Launch mobile health clinic for rural areas",
          majorGoal: false,
          functionalArea: "Health",
          comments: "Provide on-site medical consultations and treatment",
        },
        {
          goal: "Develop leadership mentorship program for women",
          majorGoal: false,
          functionalArea: "Leadership Development",
          comments: "Offer one-on-one mentoring from industry leaders",
        },
      ],
      additionalActivities: [
        {
          goal: "Host virtual workshops on mental health awareness",
          majorGoal: false,
          functionalArea: "Health",
          comments: "Offer free virtual sessions to reach a larger audience",
        },
        {
          goal: "Create online platform for community engagement",
          majorGoal: false,
          functionalArea: "Community Outreach",
          comments: "Facilitate discussions and knowledge sharing",
        },
        {
          goal: "Strengthen disaster preparedness programs",
          majorGoal: true,
          functionalArea: "Community Outreach",
          comments: "Work with local authorities to improve community response",
        },
      ],
    },
    prayerRequests: [
      "Pray for the safe launch of the mobile health clinic in rural areas",
      "Pray for successful implementation of the green energy initiatives",
    ],
    praisePoints: [
      "Praise for the successful leadership training program launch",
      "Praise for the positive impact of the agricultural support program",
    ],
    story:
      "The expansion of agricultural support has truly made a difference in the lives of local farmers, helping them increase their yield and sustainability.",
    concerns:
      "Concerns about the delay in health screenings due to supply chain issues.",
  },
];
