export const data = {
  projectAlpha: [
    {
      id: 1,
      name: "Project Alpha",
      location: "New York",
      month: "January",
      year: "2023",
      status: "Approved",
    },
    {
      id: 5,
      name: "Project Alpha",
      location: "New York",
      month: "February",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 6,
      name: "Project Alpha",
      location: "New York",
      month: "March",
      year: "2023",
      status: "Approved",
    },
    {
      id: 10,
      name: "Project Alpha",
      location: "New York",
      month: "April",
      year: "2023",
      status: "Approved",
    },
    {
      id: 14,
      name: "Project Alpha",
      location: "New York",
      month: "May",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 18,
      name: "Project Alpha",
      location: "New York",
      month: "June",
      year: "2023",
      status: "Approved",
    },
    {
      id: 22,
      name: "Project Alpha",
      location: "New York",
      month: "July",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 26,
      name: "Project Alpha",
      location: "New York",
      month: "August",
      year: "2023",
      status: "Approved",
    },
    {
      id: 30,
      name: "Project Alpha",
      location: "New York",
      month: "September",
      year: "2023",
      status: "Approved",
    },
    {
      id: 34,
      name: "Project Alpha",
      location: "New York",
      month: "October",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 38,
      name: "Project Alpha",
      location: "New York",
      month: "November",
      year: "2023",
      status: "Approved",
    },
  ],
  projectBeta: [
    {
      id: 2,
      name: "Project Beta",
      location: "Los Angeles",
      month: "February",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 7,
      name: "Project Beta",
      location: "Los Angeles",
      month: "January",
      year: "2023",
      status: "Approved",
    },
    {
      id: 11,
      name: "Project Beta",
      location: "Los Angeles",
      month: "March",
      year: "2023",
      status: "Approved",
    },
    {
      id: 15,
      name: "Project Beta",
      location: "Los Angeles",
      month: "April",
      year: "2023",
      status: "Approved",
    },
    {
      id: 19,
      name: "Project Beta",
      location: "Los Angeles",
      month: "May",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 23,
      name: "Project Beta",
      location: "Los Angeles",
      month: "June",
      year: "2023",
      status: "Approved",
    },
    {
      id: 27,
      name: "Project Beta",
      location: "Los Angeles",
      month: "July",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 31,
      name: "Project Beta",
      location: "Los Angeles",
      month: "August",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 35,
      name: "Project Beta",
      location: "Los Angeles",
      month: "September",
      year: "2023",
      status: "Approved",
    },
    {
      id: 39,
      name: "Project Beta",
      location: "Los Angeles",
      month: "October",
      year: "2023",
      status: "Submitted",
    },
  ],
  projectGamma: [
    {
      id: 3,
      name: "Project Gamma",
      location: "Chicago",
      month: "March",
      year: "2023",
      status: "Approved",
    },
    {
      id: 8,
      name: "Project Gamma",
      location: "Chicago",
      month: "April",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 12,
      name: "Project Gamma",
      location: "Chicago",
      month: "May",
      year: "2023",
      status: "Approved",
    },
    {
      id: 16,
      name: "Project Gamma",
      location: "Chicago",
      month: "June",
      year: "2023",
      status: "Approved",
    },
    {
      id: 20,
      name: "Project Gamma",
      location: "Chicago",
      month: "July",
      year: "2023",
      status: "Approved",
    },
    {
      id: 24,
      name: "Project Gamma",
      location: "Chicago",
      month: "August",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 28,
      name: "Project Gamma",
      location: "Chicago",
      month: "September",
      year: "2023",
      status: "Approved",
    },
    {
      id: 32,
      name: "Project Gamma",
      location: "Chicago",
      month: "October",
      year: "2023",
      status: "Approved",
    },
    {
      id: 36,
      name: "Project Gamma",
      location: "Chicago",
      month: "November",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 40,
      name: "Project Gamma",
      location: "Chicago",
      month: "December",
      year: "2023",
      status: "Approved",
    },
  ],
  projectDelta: [
    {
      id: 4,
      name: "Project Delta",
      location: "Houston",
      month: "April",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 9,
      name: "Project Delta",
      location: "Houston",
      month: "May",
      year: "2023",
      status: "Approved",
    },
    {
      id: 13,
      name: "Project Delta",
      location: "Houston",
      month: "June",
      year: "2023",
      status: "Approved",
    },
    {
      id: 17,
      name: "Project Delta",
      location: "Houston",
      month: "July",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 21,
      name: "Project Delta",
      location: "Houston",
      month: "August",
      year: "2023",
      status: "Approved",
    },
    {
      id: 25,
      name: "Project Delta",
      location: "Houston",
      month: "September",
      year: "2023",
      status: "Approved",
    },
    {
      id: 29,
      name: "Project Delta",
      location: "Houston",
      month: "October",
      year: "2023",
      status: "Submitted",
    },
    {
      id: 33,
      name: "Project Delta",
      location: "Houston",
      month: "November",
      year: "2023",
      status: "Approved",
    },
    {
      id: 37,
      name: "Project Delta",
      location: "Houston",
      month: "December",
      year: "2023",
      status: "Approved",
    },
  ],
};
