export const data = [
  {
    id: 1,
    project: "Project Delta",
    cluster: "Rajasthan",
    region: "North",
    facilitator: "facilitator-7",
    status: "Approved",
    type: ["The xyz is xyz", "The xyz is xyz", "The abc is xyz", "The abc is abc"],
  },
  {
    id: 2,
    project: "Project Delta",
    cluster: "Rajasthan",
    region: "East",
    facilitator: "facilitator-20",
    status: "Submitted",
    type: ["The abc is xyz", "The abc is abc", "The abc is abc"],
  },
  {
    id: 3,
    project: "Project Beta",
    cluster: "Rajasthan",
    region: "North",
    facilitator: "facilitator-6",
    status: "Approved",
    type: ["The xyz is xyz", "The xyz is xyz"],
  },
  {
    id: 4,
    project: "Project Omega",
    cluster: "Punjab",
    region: "East",
    facilitator: "facilitator-10",
    status: "Submitted",
    type: ["The xyz is xyz", "The abc is xyz"],
  },
  {
    id: 5,
    project: "Project Beta",
    cluster: "Tamil Nadu",
    region: "North",
    facilitator: "facilitator-9",
    status: "Submitted",
    type: ["The xyz is xyz", "The xyz is abc", "The abc is xyz"],
  },
  {
    id: 6,
    project: "Project Beta",
    cluster: "Punjab",
    region: "North",
    facilitator: "facilitator-2",
    status: "Submitted",
    type: ["The xyz is abc", "The abc is abc"],
  },
  {
    id: 7,
    project: "Project Gamma",
    cluster: "Punjab",
    region: "South",
    facilitator: "facilitator-2",
    status: "Approved",
    type: ["The abc is abc", "The abc is abc"],
  },
];
